--- 
abstract: Restrict ResultSets
author: Matt S Trout (mst) <mst@shadowcatsystems.co.uk>
build_requires: 
  DBD::SQLite: 0
  SQL::Translator: 0
  Scalar::Util: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Schema-RestrictWithObject
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0.07
version: 0.0001
